#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Operation
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="qds16257965_db")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void Insertshuadan_records(shuadan_records instance);
    partial void Updateshuadan_records(shuadan_records instance);
    partial void Deleteshuadan_records(shuadan_records instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::Operation.Properties.Settings.Default.qds16257965_dbConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<shuadan_records> shuadan_records
		{
			get
			{
				return this.GetTable<shuadan_records>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.shuadan_records")]
	public partial class shuadan_records : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _sdid;
		
		private string _sdgoodsname;
		
		private string _sdgoodsurl;
		
		private string _sddptype;
		
		private System.Nullable<System.DateTime> _sddate;
		
		private string _sdorderid;
		
		private string _sdphone;
		
		private string _sdvpn;
		
		private string _sdaddress;
		
		private string _sdwuliu;
		
		private string _sdremark1;
		
		private string _sdremark3;
		
		private string _sdremark2;
		
		private string _sdremark4;
		
		private string _sdremark5;
		
		private string _sdremark6;
		
		private string _sdstatepay;
		
		private string _sdremark7;
		
		private string _sdremark8;
		
		private string _sdremark9;
		
		private string _sdremark10;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnsdidChanging(int value);
    partial void OnsdidChanged();
    partial void OnsdgoodsnameChanging(string value);
    partial void OnsdgoodsnameChanged();
    partial void OnsdgoodsurlChanging(string value);
    partial void OnsdgoodsurlChanged();
    partial void OnsddptypeChanging(string value);
    partial void OnsddptypeChanged();
    partial void OnsddateChanging(System.Nullable<System.DateTime> value);
    partial void OnsddateChanged();
    partial void OnsdorderidChanging(string value);
    partial void OnsdorderidChanged();
    partial void OnsdphoneChanging(string value);
    partial void OnsdphoneChanged();
    partial void OnsdvpnChanging(string value);
    partial void OnsdvpnChanged();
    partial void OnsdaddressChanging(string value);
    partial void OnsdaddressChanged();
    partial void OnsdwuliuChanging(string value);
    partial void OnsdwuliuChanged();
    partial void Onsdremark1Changing(string value);
    partial void Onsdremark1Changed();
    partial void Onsdremark3Changing(string value);
    partial void Onsdremark3Changed();
    partial void Onsdremark2Changing(string value);
    partial void Onsdremark2Changed();
    partial void Onsdremark4Changing(string value);
    partial void Onsdremark4Changed();
    partial void Onsdremark5Changing(string value);
    partial void Onsdremark5Changed();
    partial void Onsdremark6Changing(string value);
    partial void Onsdremark6Changed();
    partial void OnsdstatepayChanging(string value);
    partial void OnsdstatepayChanged();
    partial void Onsdremark7Changing(string value);
    partial void Onsdremark7Changed();
    partial void Onsdremark8Changing(string value);
    partial void Onsdremark8Changed();
    partial void Onsdremark9Changing(string value);
    partial void Onsdremark9Changed();
    partial void Onsdremark10Changing(string value);
    partial void Onsdremark10Changed();
    #endregion
		
		public shuadan_records()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sdid", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int sdid
		{
			get
			{
				return this._sdid;
			}
			set
			{
				if ((this._sdid != value))
				{
					this.OnsdidChanging(value);
					this.SendPropertyChanging();
					this._sdid = value;
					this.SendPropertyChanged("sdid");
					this.OnsdidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sdgoodsname", DbType="VarChar(5000)")]
		public string sdgoodsname
		{
			get
			{
				return this._sdgoodsname;
			}
			set
			{
				if ((this._sdgoodsname != value))
				{
					this.OnsdgoodsnameChanging(value);
					this.SendPropertyChanging();
					this._sdgoodsname = value;
					this.SendPropertyChanged("sdgoodsname");
					this.OnsdgoodsnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sdgoodsurl", DbType="VarChar(500)")]
		public string sdgoodsurl
		{
			get
			{
				return this._sdgoodsurl;
			}
			set
			{
				if ((this._sdgoodsurl != value))
				{
					this.OnsdgoodsurlChanging(value);
					this.SendPropertyChanging();
					this._sdgoodsurl = value;
					this.SendPropertyChanged("sdgoodsurl");
					this.OnsdgoodsurlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sddptype", DbType="VarChar(500)")]
		public string sddptype
		{
			get
			{
				return this._sddptype;
			}
			set
			{
				if ((this._sddptype != value))
				{
					this.OnsddptypeChanging(value);
					this.SendPropertyChanging();
					this._sddptype = value;
					this.SendPropertyChanged("sddptype");
					this.OnsddptypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sddate", DbType="DateTime")]
		public System.Nullable<System.DateTime> sddate
		{
			get
			{
				return this._sddate;
			}
			set
			{
				if ((this._sddate != value))
				{
					this.OnsddateChanging(value);
					this.SendPropertyChanging();
					this._sddate = value;
					this.SendPropertyChanged("sddate");
					this.OnsddateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sdorderid", DbType="VarChar(5000)")]
		public string sdorderid
		{
			get
			{
				return this._sdorderid;
			}
			set
			{
				if ((this._sdorderid != value))
				{
					this.OnsdorderidChanging(value);
					this.SendPropertyChanging();
					this._sdorderid = value;
					this.SendPropertyChanged("sdorderid");
					this.OnsdorderidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sdphone", DbType="VarChar(500)")]
		public string sdphone
		{
			get
			{
				return this._sdphone;
			}
			set
			{
				if ((this._sdphone != value))
				{
					this.OnsdphoneChanging(value);
					this.SendPropertyChanging();
					this._sdphone = value;
					this.SendPropertyChanged("sdphone");
					this.OnsdphoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sdvpn", DbType="VarChar(500)")]
		public string sdvpn
		{
			get
			{
				return this._sdvpn;
			}
			set
			{
				if ((this._sdvpn != value))
				{
					this.OnsdvpnChanging(value);
					this.SendPropertyChanging();
					this._sdvpn = value;
					this.SendPropertyChanged("sdvpn");
					this.OnsdvpnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sdaddress", DbType="VarChar(500)")]
		public string sdaddress
		{
			get
			{
				return this._sdaddress;
			}
			set
			{
				if ((this._sdaddress != value))
				{
					this.OnsdaddressChanging(value);
					this.SendPropertyChanging();
					this._sdaddress = value;
					this.SendPropertyChanged("sdaddress");
					this.OnsdaddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sdwuliu", DbType="VarChar(500)")]
		public string sdwuliu
		{
			get
			{
				return this._sdwuliu;
			}
			set
			{
				if ((this._sdwuliu != value))
				{
					this.OnsdwuliuChanging(value);
					this.SendPropertyChanging();
					this._sdwuliu = value;
					this.SendPropertyChanged("sdwuliu");
					this.OnsdwuliuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sdremark1", DbType="VarChar(500)")]
		public string sdremark1
		{
			get
			{
				return this._sdremark1;
			}
			set
			{
				if ((this._sdremark1 != value))
				{
					this.Onsdremark1Changing(value);
					this.SendPropertyChanging();
					this._sdremark1 = value;
					this.SendPropertyChanged("sdremark1");
					this.Onsdremark1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sdremark3", DbType="VarChar(500)")]
		public string sdremark3
		{
			get
			{
				return this._sdremark3;
			}
			set
			{
				if ((this._sdremark3 != value))
				{
					this.Onsdremark3Changing(value);
					this.SendPropertyChanging();
					this._sdremark3 = value;
					this.SendPropertyChanged("sdremark3");
					this.Onsdremark3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sdremark2", DbType="VarChar(500)")]
		public string sdremark2
		{
			get
			{
				return this._sdremark2;
			}
			set
			{
				if ((this._sdremark2 != value))
				{
					this.Onsdremark2Changing(value);
					this.SendPropertyChanging();
					this._sdremark2 = value;
					this.SendPropertyChanged("sdremark2");
					this.Onsdremark2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sdremark4", DbType="VarChar(500)")]
		public string sdremark4
		{
			get
			{
				return this._sdremark4;
			}
			set
			{
				if ((this._sdremark4 != value))
				{
					this.Onsdremark4Changing(value);
					this.SendPropertyChanging();
					this._sdremark4 = value;
					this.SendPropertyChanged("sdremark4");
					this.Onsdremark4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sdremark5", DbType="VarChar(500)")]
		public string sdremark5
		{
			get
			{
				return this._sdremark5;
			}
			set
			{
				if ((this._sdremark5 != value))
				{
					this.Onsdremark5Changing(value);
					this.SendPropertyChanging();
					this._sdremark5 = value;
					this.SendPropertyChanged("sdremark5");
					this.Onsdremark5Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sdremark6", DbType="VarChar(500)")]
		public string sdremark6
		{
			get
			{
				return this._sdremark6;
			}
			set
			{
				if ((this._sdremark6 != value))
				{
					this.Onsdremark6Changing(value);
					this.SendPropertyChanging();
					this._sdremark6 = value;
					this.SendPropertyChanged("sdremark6");
					this.Onsdremark6Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sdstatepay", DbType="VarChar(255)")]
		public string sdstatepay
		{
			get
			{
				return this._sdstatepay;
			}
			set
			{
				if ((this._sdstatepay != value))
				{
					this.OnsdstatepayChanging(value);
					this.SendPropertyChanging();
					this._sdstatepay = value;
					this.SendPropertyChanged("sdstatepay");
					this.OnsdstatepayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sdremark7", DbType="VarChar(255)")]
		public string sdremark7
		{
			get
			{
				return this._sdremark7;
			}
			set
			{
				if ((this._sdremark7 != value))
				{
					this.Onsdremark7Changing(value);
					this.SendPropertyChanging();
					this._sdremark7 = value;
					this.SendPropertyChanged("sdremark7");
					this.Onsdremark7Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sdremark8", DbType="VarChar(255)")]
		public string sdremark8
		{
			get
			{
				return this._sdremark8;
			}
			set
			{
				if ((this._sdremark8 != value))
				{
					this.Onsdremark8Changing(value);
					this.SendPropertyChanging();
					this._sdremark8 = value;
					this.SendPropertyChanged("sdremark8");
					this.Onsdremark8Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sdremark9", DbType="VarChar(255)")]
		public string sdremark9
		{
			get
			{
				return this._sdremark9;
			}
			set
			{
				if ((this._sdremark9 != value))
				{
					this.Onsdremark9Changing(value);
					this.SendPropertyChanging();
					this._sdremark9 = value;
					this.SendPropertyChanged("sdremark9");
					this.Onsdremark9Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sdremark10", DbType="VarChar(255)")]
		public string sdremark10
		{
			get
			{
				return this._sdremark10;
			}
			set
			{
				if ((this._sdremark10 != value))
				{
					this.Onsdremark10Changing(value);
					this.SendPropertyChanging();
					this._sdremark10 = value;
					this.SendPropertyChanged("sdremark10");
					this.Onsdremark10Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
